name: devo
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.1.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - blas=1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2025.8.3
  - cachetools=5.0.0
  - certifi=2025.8.3
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - dbus=1.13.18
  - expat=2.4.4
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.11.0
  - frozenlist=1.3.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.9.1
  - google-auth-oauthlib=0.4.6
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - markdown=3.4.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - oauthlib=3.2.0
  - openh264=2.1.1
  - openssl=1.1.1w
  - pcre=8.45
  - pip=22.1.2
  - ply=3.11
  - protobuf=3.19.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.0
  - python_abi=3.10
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - pyu2f=0.1.5
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.7.2
  - setuptools=61.2.0
  - sip=6.7.12
  - sqlite=3.38.5
  - tensorboard=2.9.1
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - tomli=2.2.1
  - torchaudio=0.12.0
  - torchvision=0.13.0
  - tornado=6.1
  - tqdm=4.64.0
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.9
  - werkzeug=2.1.2
  - wheel=0.37.1
  - xz=5.2.5
  - yacs=0.1.8
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
      - argcomplete==2.0.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - attrs==25.3.0
      - beautifulsoup4==4.11.1
      - boto3==1.40.6
      - botocore==1.40.6
      - cmake==3.22.4
      - colorama==0.4.5
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - evo==1.18.1
      - filelock==3.7.1
      - fonttools==4.59.1
      - gdown==4.5.1
      - h5py==3.10.0
      - hdf5plugin==4.4.0
      - jmespath==1.0.1
      - kiwisolver==1.4.9
      - llvmlite==0.39.1
      - lz4==4.0.1
      - matplotlib==3.5.1
      - minio==7.2.16
      - natsort==8.1.0
      - numba==0.56.4
      - numpy==1.23.5
      - opencv-python==4.6.0.66
      - packaging==25.0
      - pandas==1.4.3
      - pillow==9.2.0
      - plyfile==1.1.2
      - pyarrow==21.0.0
      - pycryptodome==3.23.0
      - pygments==2.12.0
      - pyparsing==3.2.3
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.0
      - python-dateutil==2.9.0.post0
      - pytz==2022.1
      - rerun-sdk==0.14.1
      - rosbags==0.9.11
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.6
      - s3transfer==0.13.1
      - scipy==1.15.3
      - seaborn==0.11.2
      - six==1.17.0
      - soupsieve==2.3.2.post1
      - tabulate==0.9.0
      - typing-extensions==4.14.1
      - zstandard==0.18.0